webserver:
  api_root_path: ${ROOT_PATH}
indexer:
  liteserver_config: /run/secrets/tonlib_config
  ls_index: ${LITESERVER_INDEX}
  use_ext_method: ${USE_GET_BLOCK_TRANSACTIONS_EXT}
  cdll_path: ./config/libtonlibjson.so.0.5
  workers_count: ${WORKERS_COUNT}
  init_mc_seqno: ${START_SEQNO}
  smallest_mc_seqno: ${BOTTOM_SEQNO}
  blocks_per_task: 30
  max_tasks_per_child: 50
  task_time_limit: 1200
postgres:
  host: postgres
  port: 5432
  user: postgres
  password_file: /run/secrets/postgres_password
  dbname: ton_index